### ISSUE TITLE
MStatusDialog 有内存泄露问题

### ISSUE THREAD

**Issue by PiPiCaptain** [maning0303/MNProgressHUD#11]
如题

**Comment by PiPiCaptain** [comment]
个人感觉是MStatusDialog 类中的 Handler 引起的内存泄露

**Comment by maning0303** [comment]
@PiPiCaptain 感谢反馈，这个我后面跟踪一下看看。

**Comment by maning0303** [comment]
@PiPiCaptain 你再试试最新版本，我加了leakcanary检测内存问题，做了部分优化。
