### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by rsaiyuki** [maning0303/MNProgressHUD#19]
有计划适配androidx吗

**Comment by maning0303** [comment]
@rsaiyuki 后面有时间可能会考虑适配androidX,感谢反馈意见。

**Comment by geeklx** [comment]
我也遇到androidx的问题了，水平进度条和圆形的进度条不行，不显示

**Comment by maning0303** [comment]
@rsaiyuki @geeklx 已经适配了AndroidX，请查看最新的README。暂时先关闭这个Issues了，后续有什么问题再提出来。感谢。
