### ISSUE TITLE
show方法显示不出来

### ISSUE THREAD

**Issue by cvvbbo** [maning0303/MNProgressHUD#2]
MProgressDialog.Builder a = new MProgressDialog.Builder(this)
        .isCanceledOnTouchOutside(true);
        a.show();

**Comment by maning0303** [comment]
@cvvbbo   使用错了，你这里的a是一个Builder对象，你需要调用a.build();
`
MProgressDialog dialog = new MProgressDialog.Builder(this)
.isCanceledOnTouchOutside(true)
.build();
dialog.show();
`

**Comment by maning0303** [comment]
@cvvbbo  多看看Demo工程，这个我就先关闭了！
