### ISSUE TITLE
弹出dialog后导致状态颜色变化

### ISSUE THREAD

**Issue by 98Degree** [maning0303/MNProgressHUD#22]

**Comment by maning0303** [comment]
@98Degree 有没有截图可以看看具体问题？

**Comment by 98Degree** [comment]
似乎跟沉浸式有关，我把版本退回1.1.4没有此问题

**Comment by maning0303** [comment]
@98Degree 可不可以加一下我微信：13237110231方便调一下这个问题，我这边倒是发现状态栏文字颜色变化会出问题，如果是状态栏是黑色文字，显示Dialog就会变成白色文字，我这边正在加可以动态修改状态栏文字的需求。如果不是文字颜色问题，可以试试最新版本V1.1.9看看还有没有问题。

**Comment by maning0303** [comment]
@98Degree 新版本v2.0.0发布了，你可以试一下新版本，应该是主题原因导致的问题。要是还有问题就再提出来，我这边先关闭这个了，感谢。
