### ISSUE TITLE
建议加一个取消监听。

### ISSUE THREAD

**Issue by w0080626** [maning0303/MNProgressHUD#4]
既然有了可以点击外部取消。希望继续把取消的监听暴露出来，
举个栗子一个场景，我在请求接口的时候调用progressDialog 设置了可取消的属性，当dialog取消的时候直接把请求的接口也取消掉。 最后，感谢作者提供这么好的裤子，为我们减少了造轮子的时间。感谢！

**Comment by maning0303** [comment]
@w0080626 这个可以的，之前上个版本是有的，最新版本我去掉了，下个版本我在加上吧，感谢反馈！

**Comment by maning0303** [comment]
@w0080626 最新版本已经添加了dismiss监听，可以去看看README
