### ISSUE TITLE
关于MProgressBarDialog平滑过渡

### ISSUE THREAD

**Issue by xiaoli-style** [maning0303/MNProgressHUD#6]
请问在MProgressBarDialog加载的时候能否平滑过渡呢？比如从1%加载到10%，用动画平滑过渡，而不是目前较生硬的展示方式

**Comment by xiaoli-style** [comment]
(水平进度条和圆形进度条)

**Comment by maning0303** [comment]
@xiaoli-style 下版本添加这个需求，可以选择动画模式和非动画模式，感谢提出建议

**Comment by maning0303** [comment]
@xiaoli-style 新版本已经可以平滑过度了，你可以去试试看，感谢反馈。
