### ISSUE TITLE
mDialogConfig可能为空

### ISSUE THREAD

**Issue by JackChao** [maning0303/MNProgressHUD#7]
//判断是不是有监听
            if(mDialogConfig != null && mDialogConfig.onDialogDismissListener != null){
                mDialogConfig.onDialogDismissListener.onDismiss();
            }

**Comment by maning0303** [comment]
@JackChao 不会为空的，上面有对对象做判空的处理，空的话我会默认new一个。感谢反馈。下版本会考虑完善判断。
